name: simple_mood
description: A simple mood tracking application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.4+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  built_collection: ^4.3.2
  built_value: ^7.1.0
  charts_flutter: ^0.9.0
  intl: ^0.16.1
  mockito: ^4.1.1
  path: ^1.7.0
  provider: ^4.1.3
  sqflite: ^1.3.0
  shared_preferences: '>=0.5.7+3 <2.0.0'

  # Firebase
  firebase_core: "^0.7.0"
  firebase_analytics: "^7.0.1"
  firebase_crashlytics: "^0.4.0+1"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.3

# Holding off on null safety updates, until more time/support
#dependency_overrides:
#   Because charts_flutter 0.9.0 depends on intl >=0.15.2 <0.17.0, and crashlytics is actually up-to-date
#  intl: "^0.17.0-nullsafety.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build: ^1.3.0
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  flutter_launcher_icons: ^0.8.1
  source_gen: ^0.9.5

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"